"""initial_schema

Revision ID: 861451887c15
Revises: 
Create Date: 2025-11-11 07:28:40.825893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '861451887c15'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('api_key_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_projects_project_id', 'projects', ['project_id'], unique=False)
    op.create_index(op.f('ix_projects_project_id'), 'projects', ['project_id'], unique=True)
    op.create_table('entitlements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('feature_code', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.Enum('SUBSCRIPTION', 'PURCHASE', 'MANUAL', name='entitlementsource'), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'project_id', 'feature_code', 'source', 'source_id', name='uq_entitlement')
    )
    op.create_index('idx_entitlements_active', 'entitlements', ['is_active'], unique=False)
    op.create_index('idx_entitlements_feature', 'entitlements', ['feature_code'], unique=False)
    op.create_index('idx_entitlements_user_project', 'entitlements', ['user_id', 'project_id'], unique=False)
    op.create_index('idx_entitlements_valid_to', 'entitlements', ['valid_to'], unique=False)
    op.create_index(op.f('ix_entitlements_feature_code'), 'entitlements', ['feature_code'], unique=False)
    op.create_index(op.f('ix_entitlements_is_active'), 'entitlements', ['is_active'], unique=False)
    op.create_index(op.f('ix_entitlements_project_id'), 'entitlements', ['project_id'], unique=False)
    op.create_index(op.f('ix_entitlements_user_id'), 'entitlements', ['user_id'], unique=False)
    op.create_table('manual_grants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('feature_code', sa.String(length=255), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('granted_by', sa.String(length=255), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by', sa.String(length=255), nullable=True),
    sa.Column('revoke_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_manual_grants_feature', 'manual_grants', ['feature_code'], unique=False)
    op.create_index('idx_manual_grants_user_project', 'manual_grants', ['user_id', 'project_id'], unique=False)
    op.create_index('idx_manual_grants_valid_to', 'manual_grants', ['valid_to'], unique=False)
    op.create_index(op.f('ix_manual_grants_feature_code'), 'manual_grants', ['feature_code'], unique=False)
    op.create_index(op.f('ix_manual_grants_project_id'), 'manual_grants', ['project_id'], unique=False)
    op.create_index(op.f('ix_manual_grants_user_id'), 'manual_grants', ['user_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.String(length=255), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('feature_codes', sa.JSON(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'project_id', name='uq_product_project')
    )
    op.create_index('idx_products_project_id', 'products', ['project_id'], unique=False)
    op.create_index(op.f('ix_products_product_id'), 'products', ['product_id'], unique=False)
    op.create_index(op.f('ix_products_project_id'), 'products', ['project_id'], unique=False)
    op.create_table('prices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stripe_price_id', sa.String(length=255), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('interval', sa.Enum('MONTH', 'YEAR', 'ONE_TIME', name='priceinterval'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_prices_product_id', 'prices', ['product_id'], unique=False)
    op.create_index(op.f('ix_prices_product_id'), 'prices', ['product_id'], unique=False)
    op.create_index(op.f('ix_prices_stripe_price_id'), 'prices', ['stripe_price_id'], unique=True)
    op.create_table('purchases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stripe_charge_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('price_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('SUCCEEDED', 'PENDING', 'FAILED', 'REFUNDED', name='purchasestatus'), nullable=False),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['price_id'], ['prices.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_purchases_status', 'purchases', ['status'], unique=False)
    op.create_index('idx_purchases_user_project', 'purchases', ['user_id', 'project_id'], unique=False)
    op.create_index('idx_purchases_valid_to', 'purchases', ['valid_to'], unique=False)
    op.create_index(op.f('ix_purchases_price_id'), 'purchases', ['price_id'], unique=False)
    op.create_index(op.f('ix_purchases_project_id'), 'purchases', ['project_id'], unique=False)
    op.create_index(op.f('ix_purchases_status'), 'purchases', ['status'], unique=False)
    op.create_index(op.f('ix_purchases_stripe_charge_id'), 'purchases', ['stripe_charge_id'], unique=True)
    op.create_index(op.f('ix_purchases_user_id'), 'purchases', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('price_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CANCELED', 'PAST_DUE', 'TRIALING', 'UNPAID', name='subscriptionstatus'), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['price_id'], ['prices.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_subscriptions_period_end', 'subscriptions', ['current_period_end'], unique=False)
    op.create_index('idx_subscriptions_status', 'subscriptions', ['status'], unique=False)
    op.create_index('idx_subscriptions_user_project', 'subscriptions', ['user_id', 'project_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_price_id'), 'subscriptions', ['price_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_project_id'), 'subscriptions', ['project_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_subscriptions_stripe_subscription_id'), 'subscriptions', ['stripe_subscription_id'], unique=True)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_stripe_subscription_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_project_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_price_id'), table_name='subscriptions')
    op.drop_index('idx_subscriptions_user_project', table_name='subscriptions')
    op.drop_index('idx_subscriptions_status', table_name='subscriptions')
    op.drop_index('idx_subscriptions_period_end', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_purchases_user_id'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_stripe_charge_id'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_status'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_project_id'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_price_id'), table_name='purchases')
    op.drop_index('idx_purchases_valid_to', table_name='purchases')
    op.drop_index('idx_purchases_user_project', table_name='purchases')
    op.drop_index('idx_purchases_status', table_name='purchases')
    op.drop_table('purchases')
    op.drop_index(op.f('ix_prices_stripe_price_id'), table_name='prices')
    op.drop_index(op.f('ix_prices_product_id'), table_name='prices')
    op.drop_index('idx_prices_product_id', table_name='prices')
    op.drop_table('prices')
    op.drop_index(op.f('ix_products_project_id'), table_name='products')
    op.drop_index(op.f('ix_products_product_id'), table_name='products')
    op.drop_index('idx_products_project_id', table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_manual_grants_user_id'), table_name='manual_grants')
    op.drop_index(op.f('ix_manual_grants_project_id'), table_name='manual_grants')
    op.drop_index(op.f('ix_manual_grants_feature_code'), table_name='manual_grants')
    op.drop_index('idx_manual_grants_valid_to', table_name='manual_grants')
    op.drop_index('idx_manual_grants_user_project', table_name='manual_grants')
    op.drop_index('idx_manual_grants_feature', table_name='manual_grants')
    op.drop_table('manual_grants')
    op.drop_index(op.f('ix_entitlements_user_id'), table_name='entitlements')
    op.drop_index(op.f('ix_entitlements_project_id'), table_name='entitlements')
    op.drop_index(op.f('ix_entitlements_is_active'), table_name='entitlements')
    op.drop_index(op.f('ix_entitlements_feature_code'), table_name='entitlements')
    op.drop_index('idx_entitlements_valid_to', table_name='entitlements')
    op.drop_index('idx_entitlements_user_project', table_name='entitlements')
    op.drop_index('idx_entitlements_feature', table_name='entitlements')
    op.drop_index('idx_entitlements_active', table_name='entitlements')
    op.drop_table('entitlements')
    op.drop_index(op.f('ix_projects_project_id'), table_name='projects')
    op.drop_index('idx_projects_project_id', table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
